
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinetaxi?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: touqin98
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  # 配置XML映射文件中指定的实体类别名路径

  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*/*.xml
  # 开启驼峰uName自动映射到u_name
  map-underscore-to-camel-case: true